ci: Add common style check
phosh, phoc, etc use it so let's have a common on

diff --git a/ci/phosh-common-jobs.yml b/ci/phosh-common-jobs.yml
--- a/ci/phosh-common-jobs.yml
+++ b/ci/phosh-common-jobs.yml
@@ -1,6 +1,7 @@
 variables:
-  # For package builds
+  # Default image for common jobs
   PHOSH_DOCKER_IMAGE: debian:trixie
+  # For package builds
   PHOSH_PKG_GIT_SUBMODULE_UPDATE: 'true'
   PHOSH_PKG_OUTPUT_DIR: debian/output/
 
@@ -44,3 +45,25 @@ variables:
   script:
     - !reference [.phosh-prepare-apt]
     - .gitlab-ci/check-po
+
+.phosh-format-check:
+  image: ${PHOSH_DOCKER_IMAGE}
+  needs: []
+  variables:
+    PHOSH_ADDITIONAL_PKGS: git python3 uncrustify
+    GIT_DEPTH: "100"
+  script:
+    - !reference [.phosh-prepare-apt]
+    - |
+      git remote add target $CI_MERGE_REQUEST_PROJECT_URL.git
+      echo "Fetching MR target branch $CI_MERGE_REQUEST_TARGET_BRANCH_NAME from $CI_MERGE_REQUEST_PROJECT_URL"
+      git fetch target "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
+      merge_base=$(git merge-base "target/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" HEAD)
+      if [ -z "$merge_base" ]; then
+        echo "Couldn't determine merge base"
+        exit 1
+      fi
+      echo "Merge base: $merge_base"
+      ./.gitlab-ci/check-style.py --dry-run --sha $merge_base
+  rules:
+    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME'
